name: Release (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release milestone Test'
        default: '1.0.0'
        required: true
      Environment:
        description: 'Env for release'
        default: 'dev'
        required: true
      Region:
        description: 'Region for release'
        default: 'us-east-1'
        required: true
      Tag:
        description: 'Tags to select'
        default: '1.0.0,1.0.1,1.0.2'
        required: true


jobs:
  Manual-Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Version Check
        run: |
          echo "${{ github.event.inputs.version }}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
